[Distribution]
Distribution=fedora
Release=44

[Config]
Profiles=flathub,desktop,sway

[Content]
Packages =
        # hardware/drivers
        # needs extra repo
        # gstreamer1-plugin-openh264
        # openh264
        gdisk
        gvfs-mtp
        NetworkManager-openvpn
        powertop
        p11-kit-server
        tpm2-pkcs11-tools
        tpm2-pkcs11
        tpm2-tools
        # mostly for battery health/charge control
        upower

        # shell tools and development
        cyrus-sasl-plain
        fpaste
        gh
        git-delta
        isync
        krb5-workstation
        make
        mutt
        neovim
        patch
        restic
        ripgrep
        rsync
        strace
        syncthing
        tig
        w3m

        # bootstrapping mkosi/particleos Debian
        apt-utils
        debian-keyring
        pacman

        # podman
        buildah
        distrobox
        passt
        podman
        skopeo

        # desktop apps
        evince
        flatpak
        firefox
        mate-polkit
        rhythmbox
        rofimoji
        vte291

        # kitty
        kitty
        libwayland-cursor
        libwayland-egl
        mesa-libEGL

        # sway/wayland desktop
        brightnessctl
        waypipe
        wl-clipboard

VolatilePackageDirectories=../systemd/build/mkosi.builddir/fedora~rawhide~x86-64

[Build]
ExtraSearchPaths=../systemd/build
