# SPDX-License-Identifier: LGPL-2.1-or-later

# ukify calls systemd-measure for signing the PCR policy
[Match]
ToolsTreeDistribution=debian
ToolsTreeRelease=!bullseye
ToolsTreeRelease=!bookworm
ToolsTreeRelease=!trixie

[Build]
ToolsTreePackages=systemd-tpm
